#ifndef VHAVDATASOURCESTATUS_H
#define VHAVDATASOURCESTATUS_H
#include <list>
typedef enum VHAV_ACTION_ENUM_E{
    VHAV_ACTION_MONITOR,
    VHAV_ACTION_WINDOW,
    VHAV_ACTION_AREA,
    VHAV_ACTION_CAMERA,
    VHAV_ACTION_MEDIA,
    VHAV_ACTION_MIKE,
    VHAV_ACTION_SPEAKER,
    VHAV_ACTION_END
}VHAV_ACTION_ENUM;
typedef enum VHAV_STATUS_ENUM_E
{
    VHAV_STATUS_OPEND,
    VHAV_STATUS_CLOSED
}VHAV_STATUS_ENUM;
typedef std::list<std::pair<VHAV_ACTION_ENUM,VHAV_STATUS_ENUM> > VHDATA_STATUS;
bool VHAVDataSourceOperator(const VHAV_ACTION_ENUM &action,const VHAV_STATUS_ENUM &status,VHDATA_STATUS & statusList);
#endif // VHAVDATASOURCESTATUS_H
